-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
	cursor = {
		no_hardware_cursors = true,
	},
})
hl.config({
	ecosystem = {
		no_update_news = true,
	},
})

local config_dir = "~/.config/hypr"

hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "1920x0",
	scale = 1,
})

hl.monitor({
	output = "DP-1",
	mode = "1920x1080",
	position = "1920x0",
	scale = 1,
})

hl.monitor({
	output = "eDP-1",
	mode = "preferred",
	position = "0x0",
	scale = 1,
})

-- exec-once = dunst

-- exec-once = waybar & hyprpaper

-- exec-once = avizo-service

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.config({
	general = {
		gaps_in = 2,
		gaps_out = 4,
		border_size = 1,
		col = {
			active_border = { colors = { "rgba(2266ddff)" } },
			inactive_border = { colors = { "rgba(595959aa)" } },
		},
		resize_on_border = true,
		allow_tearing = false,
		layout = "master",
	},
})

hl.config({
	decoration = {
		rounding = 2,
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 6,
			color = "rgba(1a1a1aee)",
		},
		blur = {
			enabled = true,
			size = 3,
			passes = 3,
			vibrancy = 0.1696,
		},
	},
})

hl.config({
	animations = {
		enabled = true,
	},
})

hl.config({
	dwindle = {
		-- pseudotile = true
		preserve_split = true,
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = false,
	},
})

hl.config({
	input = {
		kb_layout = "de",
		kb_options = "caps:swapescape",
		numlock_by_default = true,
		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.device({
	name = "syna32b3:01-06cb:ce7d-mouse",
	sensitivity = 0.0,
})
-- NOTE: Section 'device' may be a plugin or custom section; verify the output

hl.device({
	name = "logitech-g502-hero-gaming-mouse",
	sensitivity = -0.2,
})
-- NOTE: Section 'device' may be a plugin or custom section; verify the output

hl.device({
	name = "tpps/2-elan-trackpoint",
	sensitivity = -0.5,
})
-- NOTE: Section 'device' may be a plugin or custom section; verify the output

-- source = ~/.config/hypr/custom/keybindings.conf -> requires manual conversion
-- local keybindings = require("keybindings")
-- TODO: convert ~/.config/hypr/custom/keybindings.conf to .lua and use require()
require("custom.keybindings")
require("custom.rules")
require("custom.noctalia")
-- source = ~/.config/hypr/custom/rules.conf -> requires manual conversion
-- local rules = require("rules")
-- TODO: convert ~/.config/hypr/custom/rules.conf to .lua and use require()

-- source = ~/.config/hypr/custom/noctalia.conf -> requires manual conversion
-- local noctalia = require("noctalia")
-- TODO: convert ~/.config/hypr/custom/noctalia.conf to .lua and use require()

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("/usr/local/bin/dl-sort")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("demonsend start")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
