layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}

$ipc = noctalia msg
bind = SUPER, D, exec, $ipc panel-toggle launcher
# bind = SUPER, V, exec, $ipc launcher clipboard
bind = ALT, Tab, exec, $ipc launcher windows
bind = SUPER SHIFT, L, exec, $ipc session lock
bind = SUPER SHIFT, E, exec, $ipc launcher emoji
bind = SUPER SHIFT, Q, exec, $ipc panel-toggle session
bindel = , XF86AudioRaiseVolume, exec, $ipc volume-up
bindel = , XF86AudioLowerVolume, exec, $ipc volume-down
bindl = , XF86AudioMute, exec, $ipc volume-mute
bindel = , XF86MonBrightnessUp, exec, $ipc brightness-up
bindel = , XF86MonBrightnessDown, exec, $ipc brightness-down

