-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"
hl.layer_rule({
	match = {
		namespace = "noctalia-background-.*$",
	},
	ignore_alpha = 0.5,
	blur = true,
	blur_popups = true,
})

local ipc = "qs -c noctalia-shell ipc call"

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher toggle"))

-- bind = mainMod, V, exec, $ipc launcher clipboard

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher windows"))

hl.bind(mainMod .. " + SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call lockScreen lock"))

hl.bind(mainMod .. " + SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call launcher emoji"))

hl.bind(mainMod .. " + SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call sessionMenu toggle"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume increase"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume decrease"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call volume muteOutput"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness increase"), { locked = true })

hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd("qs -c noctalia-shell ipc call brightness decrease"),
	{ locked = true }
)
