-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
-- Global Event Handling
hl.window_rule({ match = { class = ".*" }, suppress_event = "maximize" })

-- Complex focus rule for XWayland/Empty popups
hl.window_rule({
	match = {
		class = "^$",
		title = "^$",
		xwayland = 1,
		float = 1,
		fullscreen = 0,
		pin = 0,
	},
	no_focus = true,
})

-- Floating Rules (Class Match)
hl.window_rule({ match = { class = "blueman-manager" }, float = true })
hl.window_rule({ match = { class = "VirtualBox.*" }, float = true })
hl.window_rule({ match = { class = "org.raspberrypi.rpi-imager" }, float = true })
hl.window_rule({ match = { class = "sddm-conf" }, float = true })
hl.window_rule({ match = { class = "bssh" }, float = true })
hl.window_rule({ match = { class = "nwg-look" }, float = true })
hl.window_rule({ match = { class = "steam" }, float = true })
hl.window_rule({ match = { class = "textsnatcher" }, float = true })
hl.window_rule({ match = { class = "anki" }, float = true })
hl.window_rule({ match = { class = "de.unihannover.hci.quiz.QuizApplication" }, float = true })

-- Floating Rules (Title Match)
hl.window_rule({ match = { title = "Anmelden.*" }, float = true })
hl.window_rule({ match = { title = "nmtui" }, float = true })
hl.window_rule({ match = { title = "Prism.*" }, float = true })
hl.window_rule({ match = { title = "Konsolenfenster.*" }, float = true })
hl.window_rule({ match = { title = "Tic Tac Toe" }, float = true })
hl.window_rule({ match = { title = "Edit Item" }, float = true })

-- Multi-Attribute Rules
hl.window_rule({
	match = { class = "firefox", title = "Bibliothek" },
	float = true,
})

hl.window_rule({
	match = { class = "org.pulseaudio.pavucontrol" },
	float = true,
	size = { 800, 600 },
})

-- Workspace Assignments
hl.window_rule({ match = { class = "kitty" }, workspace = 1 })
hl.window_rule({ match = { class = "firefox" }, workspace = 2 })
hl.window_rule({ match = { class = "thunar" }, workspace = 3 })

-- Social Apps (Workspace 3 + No Initial Focus)
hl.window_rule({
	match = { class = "vesktop" },
	workspace = 3,
	no_initial_focus = true,
})

hl.window_rule({
	match = { class = "WebCord" },
	workspace = 3,
	no_initial_focus = true,
})

-- Workspace 4 Assignments
hl.window_rule({
	match = { class = "eu.betterbird.Betterbird" },
	workspace = 4,
	no_initial_focus = true,
})

hl.window_rule({ match = { class = "prismlauncher" }, workspace = 4 })

-- Minecraft & Console (Workspace + Float)
hl.window_rule({
	match = { title = "Minecraft.*" },
	workspace = 4,
	float = true,
})

hl.window_rule({
	match = { title = "Console window for.*" },
	workspace = 4,
	float = true,
})
